# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 147fcae5c989781ddc6690d1743653b133216c64fe62c98704c5d9130d01e030911bd45fc95bfea1c06d503d997c34943ed491adc006a87cb7ec0abf7c184762
test:
  secret_key_base: eaf10357b0e13d1ade02b8dbf9535b5f9ccdbc60cd142521383c7564c79c18d719eb5e53e1a7f362c872fbaac2334736ea0c13698860c1232d70bcf5da8bcd40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  